version: '3'

services:
  port-server:
    network_mode: host
    image: graymatics1/port-server
    build: ./server
    restart: always
    env_file:
      - ../conf/configDocker.env
    volumes:
      - ./dockerDeployment/resources:/usr/src/app/resources

  port-ui:
    image: graymatics1/port-ui
    build: ./client
    restart: always
    ports:
      - 80:80
    volumes:
      - ./dockerDeployment/nginx.conf:/etc/nginx/conf.d/default.conf
  
  port-python-server:
    network_mode: host
    image: graymatics1/port-python-server
    build: ./pythonServer
    restart: always
    volumes:
      - ./dockerDeployment/resources:/usr/src/app/resources
    env_file:
      - ../conf/configDocker.env

  port-ws:
    network_mode: host
    image: graymatics1/port-ws
    build: ./wsServer
    restart: always
    volumes:
      - ./dockerDeployment/resources:/usr/src/app/resources
    env_file:
      - ../conf/configDocker.env

  port-proxy:
    network_mode: host
    image: graymatics1/port-proxy
    build: ./proxy
    restart: always
    volumes:
      - ./dockerDeployment/resources:/usr/src/app/resources
    env_file:
      - ../conf/configDocker.env

  # port-images:
  #   network_mode: host
  #   image: graymatics1/port-images
  #   # build: ./images
  #   restart: always
  #   volumes:
  #     - ./dockerDeployment/resources:/usr/src/app/resources
  #   env_file:
  #     - ../conf/configDocker.env