version: '3'

services:
  multi-tenant-server:
    network_mode: host
    image: graymatics1/multi-tenant-server:serial-1.0.1
    restart: always
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /home/alex/Desktop/office/Multi_Tenant_App/server/configDocker.env:/usr/src/app/config.env

  multi-tenant-ui:
    image: graymatics1/multi-tenant-ui:serial-1.0.1
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/nginx.conf:/etc/nginx/conf.d/default.conf
  
  multi-tenant-pythonServer:
    network_mode: host
    image: graymatics1/multi-tenant-python:serial-1.0.1
    restart: always
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /home/alex/Desktop/office/Multi_Tenant_App/pythonServer/configPythonDocker.env:/usr/src/app/configPython.env
      