version: '3'

services:
  multi-tenant-server:
    network_mode: host
    image: graymatics1/multi-tenant-server:1.0.6
    restart: always
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /home/alex/Desktop/office/Multi_Tenant_App/configDocker.env:/usr/src/config.env

  multi-tenant-ui:
    image: graymatics1/multi-tenant-ui:1.0.3
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/nginx.conf:/etc/nginx/conf.d/default.conf
  
  multi-tenant-pythonServer:
    network_mode: host
    image: graymatics1/multi-tenant-python:1.0.2
    restart: always
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /home/alex/Desktop/office/Multi_Tenant_App/configDocker.env:/usr/src/config.env
      