version: '3'

# networks:
#   dev:
#     external: true

services:
  multi-tenant-server:
    # networks:
    #   - dev
    # ports:
    #   - "3300:3300"
    network_mode: host
    image: graymatics1/multi-tenant-server:1.1.1
    restart: always
    volumes:
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/configDocker.env:/usr/src/config.env

  multi-tenant-ui:
    image: graymatics1/multi-tenant-ui:1.1.3
    # networks:
    #   - dev
    restart: always
    ports:
      - 80:80
    volumes:
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/nginx.conf:/etc/nginx/conf.d/default.conf
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/server/resources/error.html:/usr/share/nginx/html/error/error.html
  
  multi-tenant-pythonServer:
    network_mode: host
    # ports:
    #   - "3330:3330"
    # networks:
    #   - dev
    image: graymatics1/multi-tenant-python:1.0.6
    restart: always
    volumes:
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/configDocker.env:/usr/src/config.env

  multi-tenant-ws:
    network_mode: host
    # ports:
    #   - "3301:3301"
    # networks:
    #   - dev
    image: graymatics1/multi-tenant-ws:1.0.3
    restart: always
    volumes:
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/configDocker.env:/usr/src/config.env
      - /media/alex/7f58af0e-46ef-4e1e-9e15-6c06af7846091/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      