version: '3'

services:
  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - /var/lib/mysql:/var/lib/mysql
  #   restart: always
  #   network_mode: host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: MultiTenant@123
  #     MYSQL_DATABASE: multi_tenant
  #     MYSQL_USER: graymatics
  #     MYSQL_PASSWORD: graymatics12

  multi-tenant-server:
    network_mode: host
    image: back-end
    restart: always
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/server/resources:/usr/src/app/resources
      - /home/alex/Desktop/office/Multi_Tenant_App/server/configDocker.env:/usr/src/app/config.env

  multi-tenant-ui:
    image: front-end
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/alex/Desktop/office/Multi_Tenant_App/nginx.conf:/etc/nginx/conf.d/default.conf
      