version: '3.3'

services:
  db:
     image: mysql:5.7
     volumes:
       - ${DATA_DIR}/mysql:/var/lib/mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: MultiTenant@123
       MYSQL_DATABASE: multi_tenant
       MYSQL_USER: graymatics
       MYSQL_PASSWORD: graymatics
       
  multi_tenant_server:
    depends_on:
      - db
    ports:
      - 9999:9999
      - 9998:9998
      - 9997:9997
      - 9996:9996
      - 9995:9995
    image: multi-tenant-server:0.32.4
    restart: always
    volumes:
      - /home/ubuntu/server/resources:/home/nodejs/app/resources
      - /home/ubuntu/conf/config.env:/usr/src/app/config.env
  multi_tenant_ui:
    image: multi-tenant-ui:0.30.0
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
