
version: '3.3'

services:
  db:
     image: mysql:5.7
     volumes:
       - ${DATA_DIR}/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: MultiTenant@123
       MYSQL_DATABASE: multi_tenant
       MYSQL_USER: multi_tenant
       MYSQL_PASSWORD: MultiTenant@123
       
  multi-tenant-server:
    depends_on:
      - db
    image: multi-tenant-server:0.1
    restart: always
    environment:
       PORT: 3300
       HOST: MultiTenant@123
       DB: multi_tenant
       USERM: multi_tenant
       PASSWORD: MultiTenant@123
       INSTALL: true
       NODE_ENV: production
       my_ip: localhost
       resources: resources/
       home: /usr/
       username: 'src'
       pathDocker: /app/
       secret: s0mth1ng_complicat3d-no-fac1l
    volumes:
      - ${DATA_DIR}/resources:/home/nodejs/app/resources
      - ./conf/config.env:/home/nodejs/app/config.env
  multi-tenant-ui:
    image: multi-tenant-ui:0.1
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf