version: '3'

services:
  api-server:
    network_mode: host
    image: graymatics1/api-server:1.0.1
    restart: always
    env_file:
      - ../configDocker.env
    volumes:
      - ./resources:/usr/src/app/resources

  api-proxy:
    image: graymatics1/api-proxy:1.0.1
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf