version: '3'

# networks:
#   dev:
#     external: true

services:
  multi-tenant-server:
    # networks:
    #   - dev
    # ports:
    #   - "3300:3300"
    network_mode: host
    image: graymatics1/multi-tenant-server:1.2.37
    restart: always
    volumes:
      - ./resources:/usr/src/app/resources
      - ../configDocker.env:/usr/src/config.env

  multi-tenant-ui:
    image: graymatics1/multi-tenant-ui:1.2.47
    # networks:
    #   - dev
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  
  multi-tenant-pythonServer:
    network_mode: host
    # ports:
    #   - "3330:3330"
    # networks:
    #   - dev
    image: graymatics1/multi-tenant-python:1.0.6
    restart: always
    volumes:
      - ./resources:/usr/src/app/resources
      - ../configDocker.env:/usr/src/config.env

  multi-tenant-ws:
    network_mode: host
    # ports:
    #   - "3301:3301"
    # networks:
    #   - dev
    image: graymatics1/multi-tenant-ws:1.1.7
    restart: always
    volumes:
      - ../configDocker.env:/usr/src/config.env
      - ./resources:/usr/src/app/resources
    